build: support aarch64/x86 build
    - Also use buildx instead docker to build image

Signed-off-by: Vicente Cheng <vicente.cheng@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,8 +1,19 @@
+# syntax=docker/dockerfile:1.7.0
+
 FROM registry.suse.com/bci/bci-base:15.5
 
 RUN zypper update --no-confirm && \
     zypper install --no-confirm curl iproute2 iputils nfs-client vim xfsprogs e2fsprogs zip
 
-COPY bin/harvester-csi-driver /usr/bin/
+ARG TARGETPLATFORM
+
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
+ENV ARCH=${TARGETPLATFORM#linux/}
+
+COPY bin/harvester-csi-driver-${ARCH} /usr/bin/harvester-csi-driver
 
 ENTRYPOINT ["/usr/bin/harvester-csi-driver"]
